name: Bug Report
description: Create a report to help us improve JARVIS AI
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to report a bug! Please fill out the information below.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Start app using `run.bat`
        2. Speak or send command '...'
        3. See error
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: Windows 11 / macOS Sonoma / Ubuntu 22.04
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Copy & paste relevant logs from `logs/crash.log` or `logs/err.log`.
      render: shell
